---
name: "Intros"
guid: "9482dc3b-48aa-4d3b-8224-9128d1e8e0cd"
version: "1.2.1.0"
targetAbi: "10.6.0.0"
owner: "dkanada"
overview: "Display flashy intros before movies and other videos"
description: >
  Select a flashy pre-roll from prerolls.video to run before any
  video content. The videos will be cached locally when selected
  to avoid buffering. After a new video is selected, the first
  playback event will take anywhere from 10 to 40 seconds to start
  while the pre-roll downloads.
category: "Other"
artifacts:
- "Jellyfin.Plugin.Intros.dll"
changelog: >
  Initial Release
